export const SET_VARIABLE_FALSE = '@PLACEHOLDER/SET_VARIABLE_FALSE';

export const SET_VARIABLE_TRUE = '@PLACEHOLDER/SET_VARIABLE_TRUE';

export const SET_VARIABLE_VALUE = '@PLACEHOLDER/SET_VARIABLE_VALUE';
